name: BluetoothPing
options:
  bundleIdPrefix: com.bluetoothping
  deploymentTarget:
    iOS: 12.0
  xcodeVersion: "16.2"
packages:
  RxBluetoothKit:
    url: https://github.com/RomanPodymov/RxBluetoothKit
    branch: ios-15-support
  Eureka:
    url: https://github.com/xmartlabs/Eureka
    version: 5.5.0
  Resolver:
    url: https://github.com/hmlongco/Resolver
    version: 1.5.1
targets:
  BluetoothPingApp:
    type: application
    platform: iOS
    sources: [BluetoothPing]
    dependencies:
      - package: RxBluetoothKit
      - package: Eureka
      - package: Resolver
    settings:
      base:
        SWIFT_VERSION: 6
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.bluetoothping.BluetoothPingApp
    info:
      path: BluetoothPing/Info.plist
      properties:
        NSBluetoothAlwaysUsageDescription: "We need to keep bluetooth connection to read device services and characteristics"
        NSBluetoothPeripheralUsageDescription: "We need to read data from peripherals using bluetooth"
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations: [
          UIInterfaceOrientationPortrait,
          UIInterfaceOrientationPortraitUpsideDown
        ]
    preBuildScripts:
      - script: "/opt/homebrew/bin/mint run swiftgen"
        name: SwiftGen
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 6.0"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
  BluetoothPingAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [BluetoothPingTests]
    dependencies:
      - target: BluetoothPingApp
    info:
      path: BluetoothPingTests/Info.plist
